#lang racket
(provide (all-defined-out))
(require "pa1.rkt")

;; ============================================================
;; CSCE 322 - PA2 Starter File
;;
;; In this assignment you will:
;;   1. evaluate prefix expressions generated by your PA1 code
;;   2. implement runtime type checking
;;   3. handle and propagate runtime errors
;;
;; Allowed style:
;;   - top-level define only
;;   - recursion
;;   - if / cond
;;   - basic list operations
;;
;; Not allowed:
;;   - let / let*
;;   - lambda
;;   - nested define
;;   - mutation
;;   - loops
;; ============================================================

;; ============================================================
;; Name: Duncan Holmes 
;; ============================================================


;; ============================================================
;; Error helpers
;; ============================================================

(define (type-error? x)
  (equal? x '(err "type error")))

(define (div-zero-error? x)
  (equal? x '(err "division by zero")))

(define (any-error? x)
  (and (list? x)
       (not (null? x))
       (equal? (car x) 'err)))


;; ============================================================
;; Duncan helper functions
;; ============================================================

(define (unary-bool-conditionals ast)
  (println "        unary-bool-conditionals")
  (and
    (unary-shape? ast)
    (is-unary-bool? ast)
    (eval-unary-bool ast)
  )
)

(define (negative-number-conditionals ast)
  (println "        negative-number-conditionals")
  (and
   (unary-shape? ast)
   (is-negative-number? ast)
   (eval-negative-number ast)
  )
)

(define (unary-type-error-conditionals ast)
  (println "        unary-type-error-conditionals")
  (and
   (unary-shape? ast)
   (is-unary-type-error? ast)
   (println "            Type error , for a , unary input")
   '(err "type error")
  )
)

(define (is-unary-bool-operator? e)
  (or
   (equal? e '!)
   (equal? e 'not)
  )
)

(define (is-unary-type-error? ast)
  ;;! 1
  ;;- true
  ;;not 1
  (println "            is-unary-type-error?")
  (or
   (
    and
    (is-unary-bool-operator? (my-first ast))
    (number? (my-second ast))
   )
   (
    and
    (equal? (my-first ast) '-)
    (boolean-literal? (my-second ast))
   )
  )
)

(define (is-unary-bool? ast)
  (println "            is-unary-bool?")
  (and
   (or
    (equal? (my-first ast) '!)
    (equal? (my-first ast) 'not)
   )
   (boolean-literal? (my-second ast))
   (begin
     (println "                    unary bool detected (#t)")
     #t
   )
  )
)

(define (is-negative-number? ast)
  (println "            is-negative-number?")
  (and
   (equal? (my-first ast) '-)
   (number? (my-second ast))
   (begin
     (println "                negative number detected (#t)")
     #t
   )
  )
)

(define (eval-unary-bool ast)
  (println "            eval-unary-bool")
  ;;possible correct answers:
  ;;  ! true
  ;;  ! false
  ;;  not true
  ;;  not false
  (cond
    [
     (equal? (my-second ast) 'true)
      (begin
        (println "                true -> false")
        'false
      )
    ]
    [
     (equal? (my-second ast) 'false)
      (begin
        (println "                false -> true")
        'true
      )
    ]
  )
)

(define (eval-negative-number ast)
  (println "            eval-negative-number")
  ;;like the only outcome you could have here is negative.
  ;;so just set it negative.
  (print "                ")
  (begin
    (println (- (my-second ast) (* (my-second ast) 2)) ) 
    (- (my-second ast) (* (my-second ast) 2))
  )
)

(define (eval-addition ast)
  (println "            eval-negative-number")
  (+ (my-first ast) (my-third ast))
)

;; ============================================================
;; evaluate-prefix
;;
;; Input:
;;   a valid prefix AST (generated by infix->prefix)
;;
;; Output:
;;   the evaluated value (number or boolean)
;;   OR a runtime error
;;
;; TODO:
;;   implement this function
;; ============================================================

(define (evaluate-prefix ast)
  (println "    evaluate-prefix")
  (print "   ")
  (println ast)
  
  (cond
    ;; Base cases: literals
    [(number? ast) ast]
    [(equal? ast 'true) 'true]
    [(equal? ast 'false) 'false]

    ;; TODO: handle unary operators

    ;;unary bool 
    [
     (unary-bool-conditionals ast)
    ]

    ;;negative numbers
    [
     (negative-number-conditionals ast)
    ]

    ;;error cases for unary bools
    ;;  idk any other way to do this bro
    [
     (unary-type-error-conditionals ast)
    ]
    
    ;; TODO: handle binary operators
    ;; if it's bigger than 3 items then we simplofy that using recursion down the line
    ;; when it gets to here it is 3 items
    [
     (and
      (binary-shape? ast)
      (and
       (println "        is +?")
       (equal? (my-second ast) '+)
       (eval-addition ast)
      )
     )
    ]
    ;; TODO: implement type checking
    ;; TODO: implement division by zero check
    ;; TODO: propagate errors from subexpressions

    [
     else
      ;; Placeholder
      ast
    ]
  )
)


;; ============================================================
;; evaluate-program
;;
;; Input:
;;   any Racket value (infix expression)
;;
;; Output:
;;   the evaluated value
;;   OR a PA1 syntax error
;;   OR a PA2 runtime error
;;
;; TODO:
;;   implement this function
;; ============================================================

(define (evaluate-program e)
  (cond
    ;; 1. Call your PA1 infix->prefix
    ;; 2. If it returns an error, return that error
    ;; 3. If it returns a valid AST, pass it to evaluate-prefix
    [
     else
      ;; Placeholder
      e
    ]
  )
)


;; ============================================================
;; Public test cases
;;
;; You may add more tests as you work.
;; ============================================================

;;(println "Mr T test cases")
;;(evaluate-program 5)
;; (evaluate-program '(1 + 2))
;; (evaluate-program '(1 + 2 * 3))
;; (evaluate-program '(1 + * 3))
;; (evaluate-program '(1 + true))
;; (evaluate-program '(1 / (2 - 2)))

;;(println "Barbismo test cases | unary")
;;(evaluate-prefix '(- 1))
;;(evaluate-prefix '(- true))
;;(evaluate-prefix '(- false))
;;(evaluate-prefix '(not 1))
;;(evaluate-prefix '(not true))
;;(evaluate-prefix '(not false))
;;(evaluate-prefix '(! 1))
;;(evaluate-prefix '(! true))
;;(evaluate-prefix '(! false))

;;(println "mr.t pa2 grader tests")
(evaluate-prefix '(1 + 2))
;;(evaluate-prefix '(5 - 2))
;;(evaluate-prefix '(3 * 4))
;;(evaluate-prefix '(8 / 2)))