#lang racket
(provide (all-defined-out))
(require "pa1.rkt")

;; ============================================================
;; CSCE 322 - PA2 Starter File
;;
;; In this assignment you will:
;;   1. evaluate prefix expressions generated by your PA1 code
;;   2. implement runtime type checking
;;   3. handle and propagate runtime errors
;;
;; Allowed style:
;;   - top-level define only
;;   - recursion
;;   - if / cond
;;   - basic list operations
;;
;; Not allowed:
;;   - let / let*
;;   - lambda
;;   - nested define
;;   - mutation
;;   - loops
;; ============================================================

;; ============================================================
;; Name: Duncan Holmes 
;; ============================================================


;; ============================================================
;; Error helpers
;; ============================================================

(define (type-error? x)
  (equal? x '(err "type error")))

(define (div-zero-error? x)
  (equal? x '(err "division by zero")))

(define (any-error? x)
  (and (list? x)
       (not (null? x))
       (equal? (car x) 'err)))


;; ============================================================
;; Duncan helper functions
;; ============================================================

(define (unary-bool-conditionals ast)
  (println "        unary-bool-conditionals")
  (and
    (unary-shape? ast)
    (is-unary-bool? ast)
    (eval-unary-bool ast)
  )
)

(define (negative-number-conditionals ast)
  (println "        negative-number-conditionals")
  (and
   (unary-shape? ast)
   (is-negative-number? ast)
   (eval-negative-number ast)
  )
)

(define (unary-type-error-conditionals ast)
  (println "        unary-type-error-conditionals")
  (and
   (unary-shape? ast)
   (is-unary-type-error? ast)
   (println "            Type error , from , unary input")
   '(err "type error")
  )
)

(define (is-unary-bool-operator? e)
  (or
   (equal? e '!)
   (equal? e 'not)
  )
)

(define (is-unary-type-error? ast)
  ;;! 1
  ;;- true
  ;;not 1
  (println "            is-unary-type-error?")
  (or
   (
    and
    (is-unary-bool-operator? (my-first ast))
    (number? (my-second ast))
   )
   (
    and
    (equal? (my-first ast) '-)
    (boolean-literal? (my-second ast))
   )
  )
)

(define (is-unary-bool? ast)
  (println "            is-unary-bool?")
  (and
   (or
    (equal? (my-first ast) '!)
    (equal? (my-first ast) 'not)
   )
   (boolean-literal? (my-second ast))
   (begin
     (println "                    unary bool detected (#t)")
     #t
   )
  )
)

(define (is-negative-number? ast)
  (println "            is-negative-number?")
  (and
   (equal? (my-first ast) '-)
   (number? (my-second ast))
   (begin
     (println "                negative number detected (#t)")
     #t
   )
  )
)

(define (eval-unary-bool ast)
  (println "            eval-unary-bool")
  ;;possible correct answers:
  ;;  ! true
  ;;  ! false
  ;;  not true
  ;;  not false
  (cond
    [
     (equal? (my-second ast) 'true)
      (begin
        (println "                true -> false")
        'false
      )
    ]
    [
     (equal? (my-second ast) 'false)
      (begin
        (println "                false -> true")
        'true
      )
    ]
  )
)

(define (eval-negative-number ast)
  (println "            eval-negative-number")
  ;;like the only outcome you could have here is negative.
  ;;so just set it negative.
  (print "                ")
  (begin
    (println (- (my-second ast) (* (my-second ast) 2)) ) 
    (- (my-second ast) (* (my-second ast) 2))
  )
)

(define (binary-prefix-math-shape? ast)
  (println "            binary-prefix-math-shape?")
  (and
   (arithmetic-op? (my-first ast))
   (number? (my-second ast))
   (number? (my-third ast))
  )
)

(define (adition-conditionals ast)
  (println "        adition-conditionals")
  (and
   (binary-prefix-math-shape? ast)
   (equal? (my-first ast) '+)
   (+ (my-second ast) (my-third ast))
  )
)

(define (subtraction-conditionals ast)
  (println "        subtraction-conditionals")
  (and
   (binary-prefix-math-shape? ast)
   (equal? (my-first ast) '-)
   (- (my-second ast) (my-third ast))
  )
)

(define (multiplication-conditionals ast)
  (println "        multiplication-conditionals")
  (and
   (binary-prefix-math-shape? ast)
   (equal? (my-first ast) '*)
   (* (my-second ast) (my-third ast))
  )
)

(define (divizion-conditionals ast)
  (println "        divizion-conditionals")
  (and
   (binary-prefix-math-shape? ast)
   ;;don't care about effenciy -mr.t
   (not (binary-arthimatic-divide-by-zero-error ast))
   (not (binary-arthimetic-zero-by-zero ast))
   (equal? (my-first ast) '/)
   (/ (my-second ast) (my-third ast))
  )
)

(define (binary-arthimatic-divide-by-zero-error ast)
  (println "        binary-arthimatic-divide-by-zero-error")
  ;;0 in the numerator is ok. it's just 0. 
  (and
   (binary-prefix-math-shape? ast)
   (equal? (my-first ast) '/)
   (equal? (my-third ast) 0)
    '(err "division by zero")
  )
)

(define (binary-arthimetic-zero-by-zero ast)
  (println "        binary-arthimetic-zero-by-zero")
  (and
   (binary-prefix-math-shape? ast)
   (equal? (my-first ast) '/)
   (equal? (my-second ast) '0)
   (equal? (my-third ast) '0)
   '(err "divizion of zero by 0")
  )
)


(define (1v1-boolean-and-conditions ast)
  (println "        1v1-boolean-and-conditions")
  ;;true && false
  (and
   (equal? (my-first ast) 'and)
   (boolean-literal? (my-second ast))
   (boolean-literal? (my-third ast))
   (eval-1v1-boolean-and-conditional ast)
  )
)

(define (eval-1v1-boolean-and-conditional ast)
  ;;display
  (println "            eval-1v1-boolean-and-conditional")
  (print "                ")
  (println (my-second ast))
  (print "                ")
  (println (my-third ast))
  (print "                    ")
  (println
   (and
    (equal? (my-second ast) 'true)
    (equal? (my-third ast) 'true)
   )
  )

  ;;return value
  (convert-racket-bool-to-prefix-bool
   (and
    (equal? (my-second ast) 'true)
    (equal? (my-third ast) 'true)
   )
  )
)

(define (1v1-boolean-or-conditions ast)
  (println "        1v1-boolean-or-conditions")
  ;;true || false
  (and
   (equal? (my-first ast) 'or)
   (boolean-literal? (my-second ast))
   (boolean-literal? (my-third ast))
   (eval-1v1-boolean-or-conditional ast)
  )
)

(define (convert-racket-bool-to-prefix-bool bool)
  (println "                convert-racket-bool-to-prefix-bool")
  (cond
    [
     (equal? bool #t)
     (begin
       (println "                    #t -> 'true")
       'true
     )
    ]
    [
     (equal? bool #f)
     (begin
       (println "                    #f -> 'false")
       'false
     )
    ]
  )
)

(define (eval-1v1-boolean-or-conditional ast)
  ;;display
  (println "            eval-1v1-boolean-or-conditional")
  (print "                ")
  (println (my-second ast))
  (print "                ")
  (println (my-third ast))
  (print "                    ")
  (println
   (or
    (equal? (my-second ast) 'true)
    (equal? (my-third ast) 'true)
   )
  )

  ;;return value
  (convert-racket-bool-to-prefix-bool
   (or
    (equal? (my-second ast) 'true)
    (equal? (my-third ast) 'true)
   )
  )
)

(define (1v1-number-greater-than-conditional ast)
  (println "        1v1-number-greater-than-conditional")
  (and
   (equal? (my-first ast) '>)
   (number? (my-second ast))
   (number? (my-third ast))
   (convert-racket-bool-to-prefix-bool (> (my-second ast) (my-third ast)))
  )
)

(define (1v1-number-less-than-conditional ast)
  (println "        1v1-number-less-than-conditional")
  (and
   (equal? (my-first ast) '<)
   (number? (my-second ast))
   (number? (my-third ast))
   (convert-racket-bool-to-prefix-bool (< (my-second ast) (my-third ast)))
  )
)

(define (1v1-number-greater-than-equal-to-conditional ast)
  (println "        1v1-number-greater-than-conditional")
  (and
   (equal? (my-first ast) '>=)
   (number? (my-second ast))
   (number? (my-third ast))
   (convert-racket-bool-to-prefix-bool (>= (my-second ast) (my-third ast)))
  )
)

(define (1v1-number-less-than-equal-to-conditional ast)
  (println "        1v1-number-less-than-equal-to-conditional")
  (and
   (equal? (my-first ast) '<=)
   (number? (my-second ast))
   (number? (my-third ast))
   (convert-racket-bool-to-prefix-bool (<= (my-second ast) (my-third ast)))
  )
)

(define (prefix-equal-conditional ast)
  (println "        prefix-equal-conditional")
  (and
    (equal? (my-first ast) '==)
    (convert-racket-bool-to-prefix-bool (equal? (my-second ast) (my-third ast)))
  )
)

(define (prefix-not-equal-conditional ast)
  (println "        prefix-not-equal-conditional")
  (and
    (equal? (my-first ast) '!=)
    (convert-racket-bool-to-prefix-bool (not (equal? (my-second ast) (my-third ast))))
  )
)

;; ============================================================
;; evaluate-prefix
;;
;; Input:
;;   a valid prefix AST (generated by infix->prefix)
;;
;; Output:
;;   the evaluated value (number or boolean)
;;   OR a runtime error
;;
;; TODO:
;;   implement this function
;; ============================================================

(define (evaluate-prefix ast)
  (println "    evaluate-prefix")
  (print "   ")
  (println ast)
  
  (cond
    ;; Base cases: literals
    [(number? ast) ast]
    [(equal? ast 'true) 'true]
    [(equal? ast 'false) 'false]

    ;; TODO: handle unary operators

    ;;unary bool 
    [
     (unary-bool-conditionals ast)
    ]

    ;;negative numbers
    [
     (negative-number-conditionals ast)
    ]

    ;;error cases for unary bools
    ;;  idk any other way to do this bro
    [
     (unary-type-error-conditionals ast)
    ]
    
    ;; TODO: handle binary operators
    ;; if it's bigger than 3 items then we simplofy that using recursion down the line
    ;; when it gets to here it is 3 items
    ;;     arithmatic:
    [
     (adition-conditionals ast)
    ]
    [
     (subtraction-conditionals ast)
    ]
    [
     (multiplication-conditionals ast)
    ]
    [
     (divizion-conditionals ast)
    ]
    ;;errors with binary arthmatic
    [
     (binary-arthimetic-zero-by-zero ast)
    ]
    [
     (binary-arthimatic-divide-by-zero-error ast)
    ]

    ;;1v1 boolean
    [
     (1v1-boolean-and-conditions ast)
    ]
    [
     (1v1-boolean-or-conditions ast)
    ]

    ;;1v1 number comparison
    [
     (1v1-number-greater-than-conditional ast)
    ]
    [
     (1v1-number-less-than-conditional ast)
    ]
    [
     (1v1-number-greater-than-equal-to-conditional ast)
    ]
    [
     (1v1-number-less-than-equal-to-conditional ast)
    ]
    ;;equals and not equals
    [
     (prefix-equal-conditional ast)
    ]
    [
     (prefix-not-equal-conditional ast)
    ]
    ;; TODO: implement type checking
    ;; ???
    
    ;; TODO: implement division by zero check
    ;; done above
    
    ;; TODO: propagate errors from subexpressions
    ;; done above 

    [
     else
      ;; Placeholder
      ast
    ]
  )
)


;; ============================================================
;; evaluate-program
;;
;; Input:
;;   any Racket value (infix expression)
;;
;; Output:
;;   the evaluated value
;;   OR a PA1 syntax error
;;   OR a PA2 runtime error
;;
;; TODO:
;;   implement this function
;; ============================================================

(define (evaluate-program e)
  (println "evaluate-program")
  (cond
    ;; 1. Call your PA1 infix->prefix
    ;; 2. If it returns an error, return that error
    ;; 3. If it returns a valid AST, pass it to evaluate-prefix

    ;; invalid program from infix->prefix
    [
     (any-error? (infix->prefix e))
     (infix->prefix e)
    ]

    [
     (evaluate-prefix (infix->prefix e))
    ]
    
    [
     else
      ;; Placeholder
      e
    ]
  )
)


;; ============================================================
;; Public test cases
;;
;; You may add more tests as you work.
;; ============================================================

;;(println "Mr T test cases")
;;(evaluate-program 5)
;; (evaluate-program '(1 + 2))
;; (evaluate-program '(1 + 2 * 3))
;; (evaluate-program '(1 + * 3))
;; (evaluate-program '(1 + true))
;; (evaluate-program '(1 / (2 - 2)))

;; barbismo tests
(evaluate-program '(true || false))