#lang racket
(provide (all-defined-out))
(require "pa1.rkt")

;; ============================================================
;; CSCE 322 - PA2 Starter File
;;
;; In this assignment you will:
;;   1. evaluate prefix expressions generated by your PA1 code
;;   2. implement runtime type checking
;;   3. handle and propagate runtime errors
;;
;; Allowed style:
;;   - top-level define only
;;   - recursion
;;   - if / cond
;;   - basic list operations
;;
;; Not allowed:
;;   - let / let*
;;   - lambda
;;   - nested define
;;   - mutation
;;   - loops
;; ============================================================

;; ============================================================
;; Name: Duncan Holmes 
;; ============================================================


;; ============================================================
;; Error helpers
;; ============================================================

(define (type-error? x)
  (equal? x '(err "type error")))

(define (div-zero-error? x)
  (equal? x '(err "division by zero")))

(define (any-error? x)
  ;;display
  (println "            any-error?")
  (print "                ")
  (println x)

  ;;work
  (and
   (list? x)
   (println "                x is a list")
   (not (null? x))
   (println "                x is not null")
   (equal? (car x) 'err)
  )
)


;; ============================================================
;; Duncan helper functions
;; ============================================================

(define (unary-bool-conditionals ast)
  (println "        unary-bool-conditionals")
  (and
    (unary-shape? ast)
    (is-unary-bool? ast)
    (eval-unary-bool ast)
  )
)

(define (negative-number-conditionals ast)
  (println "        negative-number-conditionals")
  (and
   (unary-shape? ast)
   (is-negative-number? ast)
   (eval-negative-number ast)
  )
)

(define (unary-type-error-conditionals ast)
  (println "        unary-type-error-conditionals")
  (and
   (unary-shape? ast)
   (is-unary-type-error? ast)
   (println "            Type error , from , unary input")
   '(err "type error")
  )
)

(define (is-unary-bool-operator? e)
  (or
   (equal? e '!)
   (equal? e 'not)
  )
)

(define (is-unary-type-error? ast)
  ;;! 1
  ;;- true
  ;;not 1
  (println "            is-unary-type-error?")
  (or
   (
    and
    (is-unary-bool-operator? (my-first ast))
    (number? (my-second ast))
   )
   (
    and
    (equal? (my-first ast) '-)
    (boolean-literal? (my-second ast))
   )
  )
)

(define (is-unary-bool? ast)
  (println "            is-unary-bool?")
  (and
   (or
    (equal? (my-first ast) '!)
    (equal? (my-first ast) 'not)
   )
   (boolean-literal? (my-second ast))
   (println "                    unary bool detected (#t)")
   #t
  )
)

(define (is-negative-number? ast)
  (println "            is-negative-number?")
  (and
   (equal? (my-first ast) '-)
   (number? (my-second ast))
   (println "                negative number detected (#t)")
   #t
  )
)

(define (eval-unary-bool ast)
  (println "            eval-unary-bool")
  ;;possible correct answers:
  ;;  ! true
  ;;  ! false
  ;;  not true
  ;;  not false
  (cond
    [
     (equal? (my-second ast) 'true)
     (println "                true -> false")
     'false
    ]
    [
     (equal? (my-second ast) 'false)
     (println "                false -> true")
     'true
    ]
  )
)

(define (eval-negative-number ast)
  (println "            eval-negative-number")
  ;;like the only outcome you could have here is negative.
  ;;so just set it negative.
  (print "                ")
  (println (- (my-second ast) (* (my-second ast) 2)) ) 
  (- (my-second ast) (* (my-second ast) 2))
)

(define (binary-prefix-math-shape? ast)
  (println "            binary-prefix-math-shape?")
  (and
   ;;display
   ;;first bool
   (println "                    (>= (length ast) 3)")
   (print "                        (>= ")
   (print (length ast))
   (println " 3)")
   (print "                        ")
   (println (>= (length ast) 3))

   (println "                    (arithmetic-op? (my-first ast))")
   (print "                        ")
   (println (arithmetic-op? (my-first ast)))

   (println "                    (number? (my-second ast))")
   (print "                        ")
   (println (number? (my-second ast)))

   ;;(println "                    (number? (my-third ast))")
   ;;(print "                        ")
   ;;(println (number? (my-third ast)))
   
   ;;final display
   (print "                ")
   (println
    (and (>= (length ast) 3)
    (arithmetic-op? (my-first ast))
    (number? (my-second ast))
    (number? (my-third ast)))
   )
   
   (>= (length ast) 3)
   (arithmetic-op? (my-first ast))
   (number? (my-second ast))
   (number? (my-third ast))
  )
)

(define (adition-conditionals ast)
  (println "        adition-conditionals")
  (and
   (binary-prefix-math-shape? ast)
   (equal? (my-first ast) '+)
   (+ (my-second ast) (my-third ast))
  )
)

(define (subtraction-conditionals ast)
  (println "        subtraction-conditionals")
  (and
   (binary-prefix-math-shape? ast)
   (equal? (my-first ast) '-)
   (- (my-second ast) (my-third ast))
  )
)

(define (multiplication-conditionals ast)
  (println "        multiplication-conditionals")
  (and
   (binary-prefix-math-shape? ast)
   (equal? (my-first ast) '*)
   (* (my-second ast) (my-third ast))
  )
)

(define (divizion-conditionals ast)
  (println "        divizion-conditionals")
  (and
   (binary-prefix-math-shape? ast)
   ;;don't care about effenciy -mr.t
   (not (binary-arthimatic-divide-by-zero-error ast))
   (not (binary-arthimetic-zero-by-zero ast))
   (equal? (my-first ast) '/)
   (/ (my-second ast) (my-third ast))
  )
)

(define (binary-arthimatic-divide-by-zero-error ast)
  (println "        binary-arthimatic-divide-by-zero-error")
  ;;0 in the numerator is ok. it's just 0. 
  (and
   (binary-prefix-math-shape? ast)
   (equal? (my-first ast) '/)
   (equal? (my-third ast) 0)
    '(err "division by zero")
  )
)

(define (binary-arthimetic-zero-by-zero ast)
  (println "        binary-arthimetic-zero-by-zero")
  (and
   (binary-prefix-math-shape? ast)
   (equal? (my-first ast) '/)
   (equal? (my-second ast) '0)
   (equal? (my-third ast) '0)
   '(err "divizion of zero by 0")
  )
)


(define (1v1-boolean-and-conditions ast)
  (println "        1v1-boolean-and-conditions")
  ;;true && false
  (and
   (equal? (my-first ast) 'and)
   (boolean-literal? (my-second ast))
   (boolean-literal? (my-third ast))
   (eval-1v1-boolean-and-conditional ast)
  )
)

(define (eval-1v1-boolean-and-conditional ast)
  ;;display
  (println "            eval-1v1-boolean-and-conditional")
  (print "                ")
  (println (my-second ast))
  (print "                ")
  (println (my-third ast))
  (print "                    ")
  (println
   (and
    (equal? (my-second ast) 'true)
    (equal? (my-third ast) 'true)
   )
  )

  ;;return value
  (convert-racket-bool-to-prefix-bool
   (and
    (equal? (my-second ast) 'true)
    (equal? (my-third ast) 'true)
   )
  )
)

(define (1v1-boolean-or-conditions ast)
  (println "        1v1-boolean-or-conditions")
  ;;true || false
  (and
   (equal? (my-first ast) 'or)
   (boolean-literal? (my-second ast))
   (boolean-literal? (my-third ast))
   (eval-1v1-boolean-or-conditional ast)
  )
)

(define (convert-racket-bool-to-prefix-bool bool)
  (println "                convert-racket-bool-to-prefix-bool")
  (cond
    [
     (equal? bool #t)
     (println "                    #t -> 'true")
     'true
    ]
    [
     (equal? bool #f)
     (println "                    #f -> 'false")
     'false
    ]
  )
)

(define (eval-1v1-boolean-or-conditional ast)
  ;;display
  (println "            eval-1v1-boolean-or-conditional")
  (print "                ")
  (println (my-second ast))
  (print "                ")
  (println (my-third ast))
  (print "                    ")
  (println
   (or
    (equal? (my-second ast) 'true)
    (equal? (my-third ast) 'true)
   )
  )

  ;;return value
  (convert-racket-bool-to-prefix-bool
   (or
    (equal? (my-second ast) 'true)
    (equal? (my-third ast) 'true)
   )
  )
)

(define (1v1-number-greater-than-conditional ast)
  (println "        1v1-number-greater-than-conditional")
  (and
   (equal? (my-first ast) '>)
   (number? (my-second ast))
   (number? (my-third ast))
   (convert-racket-bool-to-prefix-bool (> (my-second ast) (my-third ast)))
  )
)

(define (1v1-number-less-than-conditional ast)
  (println "        1v1-number-less-than-conditional")
  (and
   (equal? (my-first ast) '<)
   (number? (my-second ast))
   (number? (my-third ast))
   (convert-racket-bool-to-prefix-bool (< (my-second ast) (my-third ast)))
  )
)

(define (1v1-number-greater-than-equal-to-conditional ast)
  (println "        1v1-number-greater-than-conditional")
  (and
   (equal? (my-first ast) '>=)
   (number? (my-second ast))
   (number? (my-third ast))
   (convert-racket-bool-to-prefix-bool (>= (my-second ast) (my-third ast)))
  )
)

(define (1v1-number-less-than-equal-to-conditional ast)
  (println "        1v1-number-less-than-equal-to-conditional")
  (and
   (equal? (my-first ast) '<=)
   (number? (my-second ast))
   (number? (my-third ast))
   (convert-racket-bool-to-prefix-bool (<= (my-second ast) (my-third ast)))
  )
)

(define (prefix-equal-conditional ast)
  (println "        prefix-equal-conditional")
  (and
    (equal? (my-first ast) '==)
    (convert-racket-bool-to-prefix-bool (equal? (my-second ast) (my-third ast)))
  )
)

(define (prefix-not-equal-conditional ast)
  (println "        prefix-not-equal-conditional")
  (and
    (equal? (my-first ast) '!=)
    (convert-racket-bool-to-prefix-bool (not (equal? (my-second ast) (my-third ast))))
  )
)

(define (simplify-complicated-prefix ast)
  ;;display
  (println "        simplify-complicated-prefix")
  (print "            ")
  (println ast)

  ;;work
  (cond
    [
     (and
      (equal? ast '(err "free variable"))
      (println "            you've got a free var :-3")
      '(err "free variable")
     )
    ]
    [
     (and
      (list? (my-second ast))
      (println "            1st parameter is a list, look!")
      (print "            ")
      (println (my-second ast))
      (any-error? (evaluate-prefix (my-second ast)))
      (evaluate-prefix (my-second ast))
     )
    ]
    [
     (and
      (list? (my-third ast))
      (println "            2nd parameter is a list, look!")
      (print "            ")
      (println (my-third ast))
      (any-error? (evaluate-prefix (my-third ast)))
      (evaluate-prefix (my-third ast))
     )
    ]
    [
     (and
      (list? (my-second ast))
      (println "            1st parameter is a list, look!")
      (print "            ")
      (println (my-second ast))
      (evaluate-prefix (list (my-first ast) (evaluate-prefix (my-second ast)) (my-third ast)))
     )
    ]
    [
     (and
      (list? (my-third ast))
      (println "            2nd parameter is a list, look!")
      (print "            ")
      (println (my-third ast))
      (evaluate-prefix (list (my-first ast) (my-second ast) (evaluate-prefix (my-third ast))))
     )
    ]
    [
     (and
      (list? (my-second ast))
      (list? (my-third ast))
      (println "            both parameters are lists, look!")
      (print "            ")
      (println (my-second ast))
      (print "            ")
      (println (my-third ast))
      (evaluate-prefix (list (my-first ast) (evaluate-prefix (my-second ast)) (evaluate-prefix (my-third ast))))
     )
    ]
  )
)

(define (prefix-bool-op? e)
  (println "            prefix-bool-op")
  (or
   (equal? e 'and)
   (equal? e 'or)
  )
)

(define (numeric-comparison-op? e)
  (or
   (equal? e '>)
   (equal? e '<)
   (equal? e '>=)
   (equal? e '<=)
  )
)

(define (type-error-checker ast)
  ;;display
  (println "        type-error-checker")
  (print "            ")
  (println ast)
  
  ;;work
  (or
    (and
     (println "            previous type error ?")
     (equal? ast '(err "type error"))
    )
   
    ;; numerical 
    ;; '(1 + true) --> '(+ 1 true)
    ;; '(true < false) -> (< true false)
    (and
     (and
      (or
       (arithmetic-op? (my-first ast))
       (numeric-comparison-op? (my-first ast))
       )
      (not (unary-shape? ast))
      (not (list? (my-second ast)))
      (not (list? (my-third ast)))
      (or
       (not (number? (my-second ast)))
       (not (number? (my-third ast)))
       )
      (println "            bool in a numeric operation")
     )
     '(err "type error")
    )

    ;; boolean
    ;; '(1 && 2)
    (and
     (and
      (prefix-bool-op? (my-first ast))
      (not (unary-shape? ast))
      (not (list? (my-second ast)))
      (not (list? (my-third ast)))
      (or
       (not (boolean-literal? (my-second ast)))
       (not (boolean-literal? (my-third ast)))
      )
      (println "            numbers in a bool op")
     )
     '(err "type error")
    )

    ;; equals and not equals type error (number vs bool)
    (and
     (and
      (or
       (equal? (my-first ast) '==)
       (equal? (my-first ast) '!=)
      )
      (not (unary-shape? ast))
      (not (list? (my-second ast)))
      (not (list? (my-third ast)))
      (or
       (and
        (boolean-literal? (my-second ast))
        (number? (my-third ast))
       )
       (and
        (number? (my-second ast))
        (boolean-literal? (my-third ast))
       )
      )
      (println "            equals type error")
     )
     '(err "type error")
    )
  )
)

;; ============================================================
;; evaluate-prefix
;;
;; Input:
;;   a valid prefix AST (generated by infix->prefix)
;;
;; Output:
;;   the evaluated value (number or boolean)
;;   OR a runtime error
;;
;; ============================================================

(define (evaluate-prefix ast)
  (println "    evaluate-prefix")
  (print "        ")
  (println ast)
  
  (cond
    ;; Base cases: literals
    [(number? ast) ast]
    [(equal? ast 'true) 'true]
    [(equal? ast 'false) 'false]

    

    ;; type errors
    [
     (type-error-checker ast)
    ]

    ;; handle unary operators

    ;;unary bool 
    [
     (unary-bool-conditionals ast)
    ]

    ;;negative numbers
    [
     (negative-number-conditionals ast)
    ]

    ;;error cases for unary bools
    ;;  idk any other way to do this bro
    [
     (unary-type-error-conditionals ast)
    ]
    
    ;; handle binary operators
    ;; if it's bigger than 3 items then we simplofy that using recursion down the line
    ;; when it gets to here it is 3 items
    ;;     arithmatic:
    [
     (adition-conditionals ast)
    ]
    [
     (subtraction-conditionals ast)
    ]
    [
     (multiplication-conditionals ast)
    ]
    [
     (divizion-conditionals ast)
    ]
    ;;errors with binary arthmatic
    [
     (binary-arthimetic-zero-by-zero ast)
    ]
    [
     (binary-arthimatic-divide-by-zero-error ast)
    ]

    ;;1v1 boolean
    [
     (1v1-boolean-and-conditions ast)
    ]
    [
     (1v1-boolean-or-conditions ast)
    ]

    ;;1v1 number comparison
    [
     (1v1-number-greater-than-conditional ast)
    ]
    [
     (1v1-number-less-than-conditional ast)
    ]
    [
     (1v1-number-greater-than-equal-to-conditional ast)
    ]
    [
     (1v1-number-less-than-equal-to-conditional ast)
    ]
    
    ;;equals and not equals
    [
     (prefix-equal-conditional ast)
    ]
    [
     (prefix-not-equal-conditional ast)
    ]

    ;;recursion zone
    [
     (simplify-complicated-prefix ast)
    ]
    
    ;; implement type checking
    ;; ???
    
    ;; implement division by zero check
    ;; done above
    
    ;; propagate errors from subexpressions
    ;; done above 

    [
     else
      ;; Placeholder
      ast
    ]
  )
)


;; ============================================================
;; evaluate-program
;;
;; Input:
;;   any Racket value (infix expression)
;;
;; Output:
;;   the evaluated value
;;   OR a PA1 syntax error
;;   OR a PA2 runtime error
;;
;; ============================================================

(define (evaluate-program e)
  (println "    evaluate-program")
  (cond
    ;; 1. Call your PA1 infix->prefix
    ;; 2. If it returns an error, return that error
    ;; 3. If it returns a valid AST, pass it to evaluate-prefix

    ;;pa3:
    ;;    my pa3 functions already infix->prefix this
    ;;    and i'm not adding jank ass parameters to do it here as well
    
    ;; invalid program from infix->prefix
    ;;[
    ;; (any-error? (infix->prefix e))
    ;; (infix->prefix e)
    ;;]

    [
     ;;(evaluate-prefix (infix->prefix e))
     (evaluate-prefix e)
    ]
    
    [
     else
      ;; Placeholder
      e
    ]
  )
)
